# Neuroflow Configuration Example
# Copy to neuroflow.yaml and customize

paths:
  dicom_incoming: /media/storage/yalab-dev/test_dicom
  bids_root: /media/storage/yalab-dev/snbb_neuroflow/bids
  derivatives: /media/storage/yalab-dev/snbb_neuroflow/derivatives
  work_dir: /media/storage/yalab-dev/snbb_neuroflow/.neuroflow
  log_dir: /var/log/neuroflow

database:
  url: "sqlite:////media/storage/yalab-dev/snbb_neuroflow/.neuroflow/neuroflow.db"

redis:
  url: "redis://localhost:6379/0"

dataset:
  name: "brainbank"
  session_ids: ["baseline", "followup"]
  dicom_participant_first: true
  google_sheet:
    enabled: true
    spreadsheet_key: "1ZawIJ14Qep7r2Cs6PKI9lUVl5B2P3OKwdeTUARFQkag"
    worksheet_name: "IntegratedDatabase"
    service_account_file: "/etc/neuroflow/service-account.json"
    csv_file: ""
    scan_id_column: "ScanID"
    subject_code_column: "SubjectCode"
    unknown_subject_id: "unknown"

protocol:
  stability_wait_minutes: 180
  bids_conversion_min_files: 10

pipelines:
  bids_conversion:
    enabled: true
    tool: "heudiconv"
    version: "1.3.4"
    timeout_minutes: 60
    retries: 2
    voxelops_config:
      heuristic: "/etc/neuroflow/heuristics/brainbank.py"
      bids_validator: true
      overwrite: true
      converter: "dcm2niix"
      docker_image: "docker://nipy/heudiconv:1.3.4"
      post_process: true

  session_level:
    - name: "mriqc"
      enabled: true
      runner: "voxelops.runners.mriqc"
      container: "docker://nipreps/mriqc:24.0.0"
      timeout_minutes: 120
      requirements:
        bids_suffixes: ["T1w"]

    - name: "freesurfer"
      enabled: true
      runner: "voxelops.runners.freesurfer"
      container: "docker://freesurfer/freesurfer:7.4.1"
      timeout_minutes: 720
      requirements:
        bids_suffixes: ["T1w"]

  subject_level:
    - name: "qsiprep"
      enabled: true
      runner: "voxelops.runners.qsiprep"
      container: "docker://pennlinc/qsiprep:1.1.1"
      timeout_minutes: 720
      retries: 1
      voxelops_config:
        docker_image: "docker://pennlinc/qsiprep:1.1.1"
        fs_license: "/home/galkepler/misc/freesurfer/license.txt"
        output_resolution: 1.6
        nprocs: 8
        mem_mb: 16000
      requirements:
        bids_suffixes: ["dwi"]

    - name: "qsirecon"
      enabled: true
      runner: "voxelops.runners.qsirecon"
      container: "docker://pennlinc/qsiprep:1.1.1"
      timeout_minutes: 480
      retries: 2
      voxelops_config:
        docker_image: "docker://pennlinc/qsiprep:1.1.1"
        recon_spec: "mrtrix_multishell_msmt_ACT-hsvs"
        nprocs: 4
        mem_mb: 8000
      requirements:
        bids_suffixes: ["dwi"]

    - name: "qsiparc"
      enabled: true
      runner: "voxelops.runners.qsiparc"
      container: "docker://pennlinc/qsiprep:1.1.1"
      timeout_minutes: 240
      retries: 2
      voxelops_config:
        docker_image: "docker://pennlinc/qsiprep:1.1.1"
        atlas: "schaefer400"
        nprocs: 2
        mem_mb: 4000
      requirements:
        bids_suffixes: ["dwi"]

celery:
  worker_concurrency: 2
  task_soft_time_limit: 43200
  task_time_limit: 86400

logging:
  level: INFO
  format: console
