# Neuroflow Configuration
# Copy to neuroflow.yaml and customize

paths:
  dicom_incoming: /media/storage/yalab-dev/test_dicom
  bids_root: /media/storage/yalab-dev/snbb_neuroflow/bids
  derivatives: /media/storage/yalab-dev/snbb_neuroflow/derivatives
  work_dir: /media/storage/yalab-dev/snbb_neuroflow/.neuroflow
  log_dir: /var/log/neuroflow

execution:
  max_workers: 2
  log_per_session: true
  state_dir: /media/storage/yalab-dev/snbb_neuroflow/.neuroflow

dataset:
  name: "brainbank"
  session_ids: ["baseline", "followup"]
  dicom_participant_first: true
  google_sheet:
    enabled: true
    spreadsheet_key: "1ZawIJ14Qep7r2Cs6PKI9lUVl5B2P3OKwdeTUARFQkag"
    worksheet_name: "IntegratedDatabase"
    service_account_file: "/etc/neuroflow/service-account.json"
    csv_file: ""
    scan_id_column: "ScanID"
    subject_code_column: "SubjectCode"
    unknown_subject_id: "unknown"

protocol:
  stability_wait_minutes: 180
  bids_conversion_min_files: 10

pipelines:
  bids_conversion:
    enabled: true
    tool: "heudiconv"
    version: "1.3.4"
    timeout_minutes: 60
    retries: 2
    voxelops_config:
      heuristic: "/etc/neuroflow/heuristics/brainbank.py"
      bids_validator: true
      overwrite: true
      converter: "dcm2niix"
      docker_image: "nipy/heudiconv:1.3.4"
      post_process: true
      bids: None

  subject_level:
    - name: "qsiprep"
      enabled: true
      runner: "voxelops.runners.qsiprep"
      timeout_minutes: 720
      retries: 1
      voxelops_config:
        docker_image: "pennlinc/qsiprep:1.1.1"
        fs_license: "/home/galkepler/misc/freesurfer/license.txt"
        output_resolution: 1.6
        nprocs: 8
        mem_mb: 16000
        bids_filters: "/etc/neuroflow/bids_filters/bids_filters.json"
      requirements:
        bids_suffixes: ["dwi"]

    - name: "qsirecon"
      enabled: true
      runner: "voxelops.runners.qsirecon"
      timeout_minutes: 480
      retries: 2
      voxelops_config:
        docker_image: "pennlinc/qsirecon:1.1.2"
        nprocs: 4
        mem_mb: 8000
        datasets: {"atlases": "/media/storage/yalab-dev/voxelops/Schaefer2018Tian2020_atlases"}
        atlases: ["4S156Parcels", "Schaefer2018N100n7Tian2020S1"]
      requirements:
        bids_suffixes: ["dwi"]

    - name: "qsiparc"
      enabled: true
      runner: "voxelops.runners.qsiparc"
      timeout_minutes: 240
      retries: 2
      voxelops_config:
        nprocs: 2
        mem_mb: 4000
      requirements:
        bids_suffixes: ["dwi"]

logging:
  level: INFO
  format: console
